# mongo.configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
 mongod.conf: |
    storage:
      dbPath: /data/db
      journal:
        enabled: true
    net:
      bindIp: 0.0.0.0
    security:
      authorization: enabled
  init-replica.js: |
    rs.initiate({
      _id: "rs0",
      members: [
        { _id: 0, host: "mongo-0.mongo.default.svc.cluster.local:27017" },
        { _id: 1, host: "mongo-1.mongo.default.svc.cluster.local:27017" },
        { _id: 2, host: "mongo-2.mongo.default.svc.cluster.local:27017" }
      ]
    });
    rs.secondaryOk(); 
